name: gastos
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'
dependencies:
  animated_custom_dropdown: ^3.1.1
  animated_flip_counter: ^0.3.4
  animated_read_more_text: ^0.0.6
  badges: ^3.1.2
  cupertino_icons: ^1.0.6
  excel: ^4.0.6
  flutter:
    sdk: flutter
  flutter_animated_icons: ^1.0.1
  flutter_localizations:
    sdk: flutter
  flutter_spinbox: ^0.13.1
  get: ^4.6.6
  http: ^1.2.1
  image: ^4.2.0
  image_picker: ^1.1.2
  intl: ^0.19.0
  line_icons: ^2.0.3
  lottie: ^1.4.3
  oktoast: ^3.4.0
  path_provider: ^2.1.5
  photo_view: ^0.15.0
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  sizer: ^3.0.4
  sqflite: ^2.3.3+1
  syncfusion_flutter_calendar: ^27.1.57
  timelines_plus: ^1.0.2

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
