name: gastos
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_localizations:
    sdk: flutter
  oktoast: ^3.4.0
  provider: ^6.1.2
  sizer: ^2.0.15
  http: ^1.2.1
  shared_preferences: ^2.2.3
  flutter_spinbox: ^0.13.1
  animated_custom_dropdown: ^3.1.1
  timelines_plus: ^1.0.2
  animated_flip_counter: ^0.3.4
  intl: ^0.19.0
  image: ^4.2.0
  image_picker: ^1.1.2
  badges: ^3.1.2
  sqflite: ^2.3.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true