name: gastos
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'
dependencies:
  animated_custom_dropdown: ^3.1.1
  animated_flip_counter: ^0.3.4
  archive: ^3.6.1
  background_fetch: ^1.3.8
  badges: ^3.1.2
  calendar_date_picker2: ^2.0.0
  cupertino_icons: ^1.0.6
  dropbox_client: ^1.2.0
  excel: ^4.0.6
  file_picker: ^10.0.0
  filesize: ^2.0.1
  flutter:
    sdk: flutter
  flutter_colorpicker: ^1.1.0
  flutter_gemini: ^3.0.0
  flutter_launcher_icons: ^0.14.1
  flutter_local_notifications: ^19.2.0
  flutter_localizations:
    sdk: flutter
  flutter_spinbox: ^0.13.1
  flutter_time_picker_spinner: ^2.0.0
  get: ^4.6.6
  google_mobile_ads: ^6.0.0
  http: ^1.3.0
  image: ^4.2.0
  image_picker: ^1.1.2
  internet_connection_checker_plus: ^2.7.0
  intl: 0.20.2
  line_icons: ^2.0.3
  local_auth: ^2.3.0
  local_auth_android: ^1.0.46
  mime: ^2.0.0
  oktoast: ^3.4.0
  path: ^1.9.1
  path_provider: ^2.1.5
  percent_indicator: ^4.2.5
  photo_view: ^0.15.0
  pro_image_editor: ^9.0.2
  provider: ^6.1.2
  rive_animated_icon: ^2.0.2
  share_plus: ^11.0.0
  shared_preferences: ^2.3.3
  sizer: ^3.0.4
  sqflite: ^2.3.3+1
  substring_highlight: ^1.0.33
  syncfusion_flutter_calendar: ^29.1.33
  syncfusion_flutter_charts: ^29.2.7
  syncfusion_flutter_sliders: ^29.1.33
  timelines_plus: ^1.0.2
  timezone: ^0.10.0
  url_launcher: ^6.3.1
  youtube_player_flutter: ^9.1.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/image/icono.png"
