name: gastos
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'
dependencies:
  animated_custom_dropdown: ^3.1.1
  animated_flip_counter: ^0.3.4
  animated_read_more_text: ^0.0.6
  archive: ^3.6.1
  badges: ^3.1.2
  calendar_date_picker2: ^2.0.0
  cupertino_icons: ^1.0.6
  excel: ^4.0.6
  file_picker: ^10.0.0
  flutter:
    sdk: flutter
  flutter_colorpicker: ^1.1.0
  flutter_launcher_icons: ^0.14.1
  flutter_localizations:
    sdk: flutter
  flutter_spinbox: ^0.13.1
  get: ^4.6.6
  giffy_dialog: ^2.3.0
  google_mobile_ads: ^5.2.0
  http: ^1.3.0
  image: ^4.2.0
  image_picker: ^1.1.2
  internet_connection_checker_plus: ^2.7.0
  intl: ^0.19.0
  line_icons: ^2.0.3
  liquid_progress_indicator_v2: ^0.5.0
  local_auth: ^2.3.0
  local_auth_android: ^1.0.46
  mime: ^2.0.0
  oktoast: ^3.4.0
  path_provider: ^2.1.5
  photo_view: ^0.15.0
  pro_image_editor: ^9.0.2
  provider: ^6.1.2
  rive_animated_icon: ^2.0.2
  share_plus: ^10.1.2
  shared_preferences: ^2.3.3
  sizer: ^3.0.4
  sqflite: ^2.3.3+1
  substring_highlight: ^1.0.33
  syncfusion_flutter_calendar: ^29.1.33
  syncfusion_flutter_sliders: ^29.1.33
  timelines_plus: ^1.0.2
  youtube_player_flutter: ^9.1.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/image/icono.png"
